/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMenu: typeof import('./src/components/AppMenu.vue')['default']
    BAccordion: typeof import('bootstrap-vue-next')['BAccordion']
    BAccordionItem: typeof import('bootstrap-vue-next')['BAccordionItem']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BBreadcrumb: typeof import('bootstrap-vue-next')['BBreadcrumb']
    BBreadcrumbItem: typeof import('bootstrap-vue-next')['BBreadcrumbItem']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next')['BFormInvalidFeedback']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    BreadcrumbTwo: typeof import('./src/components/BreadcrumbTwo.vue')['default']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    CartItem: typeof import('./src/components/widgets/CartItem.vue')['default']
    CartOffcanvas: typeof import('./src/components/NavBar/CartOffcanvas.vue')['default']
    FlatPicker: typeof import('./src/components/FlatPicker.vue')['default']
    Jarallax: typeof import('./src/components/Jarallax.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    LeafletMap: typeof import('./src/components/LeafletMap.vue')['default']
    LightGallery: typeof import('./src/components/LightGallery.vue')['default']
    LogoBox: typeof import('./src/components/NavBar/LogoBox.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    MenuItemWithChildren: typeof import('./src/components/MenuItemWithChildren.vue')['default']
    NavBar: typeof import('./src/components/NavBar/NavBar.vue')['default']
    NavBar2: typeof import('./src/components/NavBar/NavBar2.vue')['default']
    NavBar3: typeof import('./src/components/NavBar/NavBar3.vue')['default']
    Parallax: typeof import('./src/components/Parallax.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    Preloader: typeof import('./src/components/Preloader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchModal: typeof import('./src/components/NavBar/SearchModal.vue')['default']
    ShuffleJS: typeof import('./src/components/ShuffleJS.vue')['default']
    ThemeCustomizer: typeof import('./src/components/ThemeCustomizer/index.vue')['default']
    ThemeSwitcher: typeof import('./src/components/NavBar/ThemeSwitcher.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next')['vBToggle']
  }
}
